Arguments: 
  /usr/local/bin/node /usr/local/bin/yarn add --dev hardhat @openzeppelin/contracts typescript typechain ts-node @typechain/ethers-v5 @typechain/hardhat @types/chai @types/node hardhat-deploy @nomiclabs/hardhat-ethers@npm:hardhat-deploy-

PATH: 
  /Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/derek/opt/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Frameworks/Python.framework/Versions/3.8/bin:/Users/derek/opt/anaconda3/bin

Yarn version: 
  1.22.18

Node version: 
  16.15.0

Platform: 
  darwin x64

Trace: 
  Error: https://registry.yarnpkg.com/hardhat-deploy-: Not found
      at Request.params.callback [as _callback] (/usr/local/lib/node_modules/yarn/lib/cli.js:66138:18)
      at Request.self.callback (/usr/local/lib/node_modules/yarn/lib/cli.js:140883:22)
      at Request.emit (node:events:527:28)
      at Request.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:141855:10)
      at Request.emit (node:events:527:28)
      at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/yarn/lib/cli.js:141777:12)
      at Object.onceWrapper (node:events:641:28)
      at IncomingMessage.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21)

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile
